# Generated by Django 3.0.3 on 2021-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceries',
            name='status',
            field=models.CharField(choices=[('0', 'PENDING'), ('1', 'BOUGHT'), ('2', 'NOT AVAILABLE')], default='0', max_length=20),
        ),
    ]
